### PR TITLE
phone login support

### PR DESCRIPTION
**Pull request by ujwal-setlur**
Hi I have added phone login support. This requires the ujwal:accounts-phone package. Would be great if this can be merged. Thanks!

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
This is so badass, sorry for seeing it this late. This requires also good docs and indented code. But super nice! I'm gonna take care of it if you don't find the time!

Talking about this:
```
+mutation createUserWithPhone {
+      createUserWithPhone (phone: "+11234567890", profile: {name: "A Phone User"}) {
+			success
+      }
+    }
```

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, great! I will try to clean up the code and docs this weekend.

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, great! I will try to clean it up this weekend! Thanks!

**Comment by ujwal-setlur** [comment]
I have updated the pull request and also resolved https://github.com/cult-of-coders/apollo/issues/52

**Comment by ujwal-setlur** [comment]
@theodorDiaconu, thoughts on merging this?

**Pull request merged**
